### ISSUE TITLE
NVME SSD very slow for grub4dos loading VHD to RAM

### ISSUE THREAD

**Issue by wimbrts** [chenall/grub4dos#259]
I have [measured the time to Load](http://reboot.pro/index.php?showtopic=21977&p=217958) [Mini-10x64 VHD](https://msfn.org/board/topic/182020-mini-10x64-in-vhd/) to RAM for booting as RAMDISK.

[grub4dos-for_UEFI-2021-02-10.7z](https://github.com/chenall/grub4dos/releases) in UEFI mode and [grub4dos-0.4.6a-2021-01-27.7z](https://github.com/chenall/grub4dos/releases) for MBR BIOS mode were used.

The time in seconds to Load VHD to RAM was measured for NVME SSD and SATA SSD and USB SSD

bootdisk type    [Mini-10x64 VHD](https://github.com/wimbrts/VHD_WIMBOOT/releases) 3900 MB
 
NVME SSD UEFI - Load VHD to RAM =  65 seconds
NVME SSD MBR - Load VHD to RAM =  83 seconds
 
SATA SSD UEFI  - Load VHD to RAM =  38 seconds
SATA SSD MBR  - Load VHD to RAM =  15 seconds
 
USB  SSD UEFI  - Load VHD to RAM =  55 seconds
USB  SSD MBR  - Load VHD to RAM =  32 seconds

How come that NVME SSD is so much slower than SATA SSD for grub4dos Loading VHD to RAM ?

**Comment by Taviruni** [comment]
@yaya2007 and @a1ive

Only hope this info could be of some help.

It seems very clear grub4dos v0.46a (MBR and UEFI versions) reading speed of NVME devices is very slow.

There is a patch for grub4dos 0.45c made by **Kai Schtrom**'s (also author of SVBus driver): **Grub4DOS AHCI/NVMe speed patch for memory maps**, maybe it could be adapted to make it work on v0.46a, or useful to get some ideas to improve the reading speed of NVME devices, for more info please see: 

https://sourceforge.net/projects/grub4dosahcipatch/ and this topic on reboot.pro: http://reboot.pro/index.php?showtopic=21872

Your friend
alacran (from reboot.pro)

**Comment by a1ive** [comment]
> @yaya2007 and @a1ive
> 
> Only hope this info could be of some help.
> 
> It seems very clear grub4dos v0.46a (MBR and UEFI versions) reading speed of NVME devices is very slow.
> 
> There is a patch for grub4dos 0.45c made by **Kai Schtrom**'s (also author of SVBus driver): **Grub4DOS AHCI/NVMe speed patch for memory maps**, maybe it could be adapted to make it work on v0.46a, or useful to get some ideas to improve the reading speed of NVME devices, for more info please see:
> 
> https://sourceforge.net/projects/grub4dosahcipatch/ and this topic on reboot.pro: http://reboot.pro/index.php?showtopic=21872
> 
> Your friend
> alacran (from reboot.pro)

https://ci.appveyor.com/project/chenall/grub4dos/builds/38447690/artifacts
please try.

**Comment by a1ive** [comment]
> How come that NVME SSD is so much slower than SATA SSD for grub4dos Loading VHD to RAM ?

grub (and other bootloaders) use the API provided by the firmware (BIOS/UEFI) to read the disk, and the speed is determined by the firmware's drivers.

**Comment by wimbrts** [comment]
> https://ci.appveyor.com/project/chenall/grub4dos/builds/38447690/artifacts
> please try.

Thanks for making test version of grub4dos.
The speed for MBR grub4dos Loading Mini-10x64 VHD to RAM is about the same
NVME SSD MBR - Load VHD to RAM = 84 seconds

**Comment by steve6375** [comment]
As a1ive says, the speed will be dependent on the driver code used by the BIOS. So the code used for the NVME interface, SATA interface and USB (2/3) interface will be different. Also the drivers used for UEFI and Legacy will be different. So we are talking about 6 different drivers inside the specific BIOS in you system.
Each driver can be written to use one of many different protocols and can be polling, be interrupt driven, DMA-driven or a combination. Not only is the driver code a factor, but also the drive's controller performance in that particular mode is a factor.
When an Operating System driver is loaded, it will use a much more sophisticated driver and can use better/faster block transfer protocols.
So the end result will depend on the BIOS code (different BIOSes on different PCs/notebooks will produce different results) and the peculiarities of each drive's controller which may be ultra-fast when using some protocols, but very slow when using other protocols such as more simple single-block transfer protocols using polling or interrupts.
So just because your particular drives give these results on you particular BIOS, it does not mean the same effect will be seen when using different drives (controllers) and different BIOSes.
You should also bear in mind that the filesystem used is also a factor and so must always be the same between devices as should the approximate size of the formatted volume used - these also affect timings.

**Comment by a1ive** [comment]
> > https://ci.appveyor.com/project/chenall/grub4dos/builds/38447690/artifacts
> > please try.
> 
> Thanks for making test version of grub4dos.
> The speed for MBR grub4dos Loading Mini-10x64 VHD to RAM is about the same
> NVME SSD MBR - Load VHD to RAM = 84 seconds

This is used to test Kai Schtrom's AHCI & NVME patch applied to 0.4.6a.

**Comment by wimbrts** [comment]
@steve6375 
@a1ive 
Thanks both of you for comment on NVME SSD speed for grub4dos Loading of VHD to RAM

It seems that the BIOS drivers determine the results.
Differences in speed of Loading to RAM are striking and it is good to know which interface is best.
I can live with that and will use MBR grub4dos booting from SATA SSD and will not use NVME SSD for loading to RAM.

**Comment by wimbrts** [comment]
Good News !
After BIOS/UEFI firmware Update the NVME SSD speed to [Load PE WIM and Mini-10x64 VHD to RAM](http://reboot.pro/index.php?showtopic=21977&p=217995) is very much improved.
Now NVME SSD UEFI is clearly the winner in loading 3900 MB VHD in only 3 seconds to RAM instead of 65 seconds before Update.
Also NVME SSD MBR Grub4dos is much better in loading 3900 MB VHD in 20 seconds to RAM instead of 83 sec before Update.

bootdisk type Mini-10x64 VHD 3900 MB

NVME SSD UEFI - Load VHD to RAM = 65 seconds  and  3 seconds After firmware Update
NVME SSD MBR - Load VHD to RAM = 83 seconds and 20 seconds After firmware Update

SATA SSD UEFI - Load VHD to RAM = 38 seconds and  38 seconds After firmware Update
SATA SSD MBR - Load VHD to RAM = 15 seconds and  13 seconds After firmware Update

USB SSD UEFI - Load VHD to RAM = 55 seconds and 55 seconds After firmware Update
USB SSD MBR - Load VHD to RAM = 32 seconds and  32 seconds After firmware Update

**Comment by yaya2007** [comment]
That's good news. 
Once again, the read and write speed of SSD depends on BIOS .
Estimation is a problem of 4K boundary alignment.

**Comment by wimbrts** [comment]
> That's good news.
> Once again, the read and write speed of SSD depends on BIOS .
> Estimation is a problem of 4K boundary alignment.

Thanks for your info and reply.

More Info on [all measurements](http://reboot.pro/index.php?showtopic=21977&p=217995) and [equipment used](http://reboot.pro/index.php?showtopic=21977&p=217999) are given at reboot.pro forum.
