### ISSUE TITLE
grub4efi - support for wimboot and booting Windows Install ISOs

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#290]
Is it possible to support wimboot (as used in a1ive grub2) to boot .wim files?
I want to uefi-boot directly from a Windows 10 ISO and use wimboot to inject files into the X: drive, etc. same as possible with a1ive grub2/grubfm.
Using kernel /wimboot command on  ipxe wimboot file https://ipxe.org/wimboot returns 
`'kernel too old (0x0203 < 0x020b)`
a1ive ntloader does not seem to work with (0xff) devices mapped to ISOs and cannot inject files into the X: drive?
https://github.com/grub4dos/ntloader

**Comment by a1ive** [comment]
> Is it possible to support wimboot (as used in a1ive grub2) to boot .wim files?

1. you need to patch wimboot to make it support the [Linux x86 EFI Handover Protocol](https://www.kernel.org/doc/html/latest/x86/boot.html#efi-handover-protocol-deprecated), which is the only protocol supported by grub4efi for booting linux kernel.
- https://lists.ipxe.org/pipermail/ipxe-devel/2018-November/006338.html
- https://lists.ipxe.org/pipermail/ipxe-devel/2018-November/006339.html
- https://lists.ipxe.org/pipermail/ipxe-devel/2018-November/006340.html
- https://lists.ipxe.org/pipermail/ipxe-devel/2018-November/006341.html
2. Currently grub4efi does not support generating initrd in cpio newc format (@boot.wim=xxx), and since only iPXE wimboot needs this and it cannot boot under grub4efi, there is no need for grub4efi to add this feature.
3. The above patch is not perfect. It does not work on some computers and has been reported by many people. (ntloader has a similar problem)

**Comment by steve6375** [comment]
So how can we boot to Windows Install ISO and install Windows?
So the only way is to allow Setup to autodetect \autounattend.xml file on USB drive (old method which does not work with older Windows 7/8 ISOs as they do not detect xml files on USB HDDs - only USB flash/removable drives).

**Comment by a1ive** [comment]
> So how can we boot to Windows Install ISO and install Windows?

That's your headache now, not mine. 😆 
I would not port wimboot to grub4dos commands (or external commands), porting would be far more difficult than grub2.
The following are my suggestion:
Make an img image containing my grub2 and a special menu.cfg, map it to a virtual disk under grub4efi and then modify the menu.cfg with `dd` command so that you can boot the wim file via grub4efi->grub2 wimboot.
Of course you can also replace my grub2 with another bootloader, such as iPXE +wimboot or Ventoy.

**Comment by steve6375** [comment]
That is really very disappointing :-(
Your grub2 is discontinued (not active)
Ventoy will never make any changes for other applications.
grub4efi will never become a serious USB multiboot solution if it cannot support booting from Windows Install ISOs...

**Comment by a1ive** [comment]
> grub4efi will never become a serious USB multiboot solution if it cannot support booting from Windows Install ISOs...

Creating an img with grub2 bootx64.efi and modifying the menu with the `dd` command is much easier than porting wimboot.
I don't see the value in porting wimboot all over again.

> Your grub2 is discontinued (not active)

Yes and no.
I no longer want to use the name "GRUB" to develop a bootloader.
The name causes confusion and (perhaps) implies compatibility with other GRUBs. Also I am not happy with some of the early code I wrote which introduced some bugs that were not easily fixed.
So I stopped maintaining a1ive GRUB2 and instead considered developing a [new bootloader](https://github.com/grub4dos/Prethoryn), which, although based on GRUB, I would no longer keep it compatible with GRUB. This project is still in early stages.
P.S. I also don't like the project name "GRUB4DOS". Currently 99% of users will not use it under DOS.

**Comment by steve6375** [comment]
Since E2B has grubfm already on 2nd partition, I have implemented a mechanism for grub4efi to chainload grubfm on the 2nd partition and run win.sh to load a windows ISO.
I was hoping to replace grubfm with grub4efi because of the inherent bugs in grub2 and it's graphical menu system, etc.
I really hope someone can port the ipxe wimboot code to grub4efi (can the Ventoy code be used?).
I am really impressed by all the work that has gone into grub4efi, but if it cannot load Windows install ISOs then that is a really BIG limitation.
