### ISSUE TITLE
{partnew} command not working as expected 

### ISSUE THREAD

**Issue by anwar-alsilwy** [chenall/grub4dos#374]
Hi
I tried to delete & restore partition using {partnew} command, for example partition #4:
on Grub4dos (legacy) I typed command :
partnew (hd0,3) 0 0 0 0
so, all (type, begin CHS, end CHS, start & length) values cleared and become 0
But when I tried to restore partition #4, something wrong happened:

A: on Grub4dos (legacy) after restore the partition, the CHS values are not identical like original previous values, it's look like a bug, see pic:
![g4d_legacy](https://user-images.githubusercontent.com/71539261/188120726-94e43095-3ed9-4681-9ba2-039b38187b78.png)

B: on Grub4dos (UEFI) the results it's even worse, after restore the partition, the CHS values was still empty 0/0/0, and it's look like another bug too, see pic:
![g4d_UEFI](https://user-images.githubusercontent.com/71539261/188121677-288be8d9-a9d0-48e7-ab43-3b243c96c728.png)

C: on grub2 (A1ive grubfm) I tried to restore Partition 4#, but this time all values including (type, begin CHS, end CHS, start & length) have returned to the original previous values, and that's 100% perfect, see pic:
![A1ive](https://user-images.githubusercontent.com/71539261/188123027-15a15133-c6b9-4bae-8643-6ec7db3df2ae.png)

{partnew} command is very necessary feature on grub4dos, So I hope you take a look, and fix this bug soon.

Thanks for your hard work.

**Comment by yaya2007** [comment]
Grub4dos (Legacy) determines the C / h / S parameters through internal function geometric detection, which is the advantage of grub4dos (Legacy) different from other boot programs. It is an advantage and a key point with a high probability of success.

Does the change of C / h / s affect the boot function? This is the key!

Grub4dos (UEFI) boot has nothing to do with C / h / s, I don't care about it, let alone handle it.

#373 you didn't answer. There is a help message. Can be executed from the command line
help hiddenflag

hiddenflag --clear] [PARTITION]
It's unhide

**Comment by steve6375** [comment]
If over 8GB then 1023 254 63 should be used for CHS.

https://en.wikipedia.org/wiki/Master_boot_record#Partition_table_entries
When a CHS address is too large to fit into these fields, the [tuple](https://en.wikipedia.org/wiki/Tuple) **(1023, 254, 63) is typically used today**, although on older systems, and with older disk tools, the cylinder value often wrapped around modulo the CHS barrier near 8 GB, causing ambiguity and risks of data corruption. (If the situation involves a "protective" MBR on a disk with a GPT, Intel's [Extensible Firmware Interface](https://en.wikipedia.org/wiki/Extensible_Firmware_Interface) specification requires that the tuple (1023, 255, 63) be used.) The 10-bit cylinder value is recorded within two bytes in order to facilitate making calls to the original/legacy [INT 13h](https://en.wikipedia.org/wiki/INT_13h) BIOS disk access routines, where 16 bits were divided into sector and cylinder parts, and not on byte boundaries.[[14]](https://en.wikipedia.org/wiki/Master_boot_record#cite_note-Phoenix_1989_System-BIOS-18)

The CHS addressing supported in IBM-PC compatible [BIOSes](https://en.wikipedia.org/wiki/BIOS) code used eight bits for - theoretically up to 256 heads counted as head 0 up to 255 (FFh). However, a bug in all versions of [Microsoft DOS](https://en.wikipedia.org/wiki/MS-DOS)/[IBM PC DOS](https://en.wikipedia.org/wiki/IBM_PC_DOS) up to and including 7.10 will cause these operating systems to crash on boot when encountering volumes with 256 heads[[2]](https://en.wikipedia.org/wiki/Cylinder-head-sector#endnote_b). Therefore, all compatible BIOSes will use mappings with up to 255 heads (00h..FEh) only, including in virtual 255×63 geometries.
https://en.wikipedia.org/wiki/Cylinder-head-sector#CHS_to_LBA_mapping

**Comment by yaya2007** [comment]
Please test
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/9492818/grldr.rar.txt)
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/9492820/BOOTX64.rar.txt)
